# Generated by Django 6.0.4 on 2026-05-22 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('honest_restaurant', '0017_alter_publicrestaurantdata_hygiene_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '생성 대기'), ('done', '생성 완료'), ('failed', '생성 실패')], db_index=True, default='pending', max_length=10, verbose_name='상태')),
                ('report_text', models.TextField(blank=True, verbose_name='리포트 본문')),
                ('push_message', models.TextField(blank=True, verbose_name='푸시 알림 메시지')),
                ('period_start', models.DateField(verbose_name='분석 시작일')),
                ('period_end', models.DateField(verbose_name='분석 종료일')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='생성 완료 시각')),
                ('error_msg', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='honest_restaurant.publicrestaurantdata', verbose_name='식당')),
            ],
            options={
                'verbose_name': 'AI 리포트',
                'verbose_name_plural': 'AI 리포트',
                'db_table': 'restaurant_ai_report',
                'ordering': ['-period_end'],
            },
        ),
    ]
