# Generated by Django 6.0.4 on 2026-05-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='gemini-2.5-flash', max_length=100, verbose_name='AI 모델명')),
                ('temperature', models.FloatField(default=1.0, verbose_name='Temperature (0.0 ~ 2.0)')),
                ('report_period_days', models.PositiveIntegerField(default=90, verbose_name='분석 기간 (일)')),
                ('role_description', models.TextField(default='당신은 식당 사장님에게 운영 인사이트를 전달하는 친절한 AI 어시스턴트입니다.\n아래 최근 {period_days}일 고객 리뷰 분석 데이터를 바탕으로 리포트를 작성해주세요.', verbose_name='AI 역할 설명')),
                ('writing_rules', models.TextField(default='1. 사장님을 "사장님"으로 호칭\n2. 가장 눈에 띄는 긍정 포인트 1가지를 먼저 언급\n3. 개선이 필요한 부분이 있으면 부드럽게 제안 (없으면 생략)\n4. 위생 경고가 있으면 반드시 포함\n5. 전체 3~4문장, 친근하고 실용적인 말투\n6. 이모지 1~2개만 사용\n7. 마케팅 문구나 과장 표현 금지', verbose_name='작성 규칙')),
            ],
            options={
                'verbose_name': 'AI 리포트 설정',
                'verbose_name_plural': 'AI 리포트 설정',
                'db_table': 'ai_report_config',
            },
        ),
    ]
