# Generated by Django 6.0.4 on 2026-05-06 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '검토 중'), ('approved', '인증 완료'), ('rejected', '인증 거부')], default='pending', max_length=10, verbose_name='인증 상태')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='honest_restaurant.publicrestaurantdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '영수증 인증',
                'verbose_name_plural': '영수증 인증',
                'unique_together': {('restaurant', 'user')},
            },
        ),
    ]
