# Generated by Django 6.0.4 on 2026-05-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0005_restaurantmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicrestaurantdata',
            name='name',
            field=models.CharField(db_index=True, help_text='[필수] 사업자등록증 명칭과 자동 대조 → LV2 검증', max_length=200, verbose_name='업소명'),
        ),
    ]
