# Generated by Django 6.0.4 on 2026-05-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0007_publicrestaurantdata_restaurant_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='publicrestaurantdata',
            constraint=models.UniqueConstraint(condition=models.Q(('address_road__gt', '')), fields=('name', 'address_road', 'business_type'), name='uq_name_road_biztype'),
        ),
    ]
