# Generated by Django 6.0.4 on 2026-05-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0010_add_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicrestaurantdata',
            options={'ordering': ['-synced_at'], 'verbose_name': '공공 음식점 데이터', 'verbose_name_plural': '공공 음식점 데이터'},
        ),
        migrations.RemoveField(
            model_name='publicrestaurantdata',
            name='license_cancel_date',
        ),
        migrations.RemoveField(
            model_name='publicrestaurantdata',
            name='restaurant_type',
        ),
        migrations.AlterField(
            model_name='publicrestaurantdata',
            name='district',
            field=models.CharField(blank=True, db_index=True, help_text='주소의 두 번째 단위 (구·시·군). 상권별 분석 & 지자체 B2G 리포트', max_length=20, verbose_name='자치구/시/군'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
