# Generated by Django 6.0.4 on 2026-05-18 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0011_alter_publicrestaurantdata_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publicrestaurantdata',
            name='idx_district_status',
        ),
        migrations.RemoveIndex(
            model_name='publicrestaurantdata',
            name='idx_district_status_synced',
        ),
        migrations.RemoveField(
            model_name='publicrestaurantdata',
            name='district',
        ),
    ]
