# Generated by Django 6.0.4 on 2026-05-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0012_remove_district_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='hygiene_grade',
            field=models.CharField(blank=True, help_text='식품의약품안전처 위생등급 (예: 적합) — C004 API 연동', max_length=20, verbose_name='위생등급'),
        ),
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='hygiene_grade_from',
            field=models.DateField(blank=True, null=True, verbose_name='위생등급 지정일'),
        ),
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='hygiene_grade_no',
            field=models.CharField(blank=True, help_text='위생등급 지정 번호 (예: 제HG240625891호)', max_length=50, verbose_name='위생등급 번호'),
        ),
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='hygiene_grade_to',
            field=models.DateField(blank=True, null=True, verbose_name='위생등급 만료일'),
        ),
    ]
