# Generated by Django 6.0.4 on 2026-05-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0013_add_hygiene_grade_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='excellent_dsgn_ymd',
            field=models.DateField(blank=True, null=True, verbose_name='모범음식점 지정일'),
        ),
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='excellent_food_type',
            field=models.CharField(blank=True, help_text='예: 한식, 중식', max_length=50, verbose_name='음식 종류'),
        ),
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='excellent_main_menu',
            field=models.CharField(blank=True, help_text='예: 차돌짬뽕, 손칼국수', max_length=100, verbose_name='대표 메뉴'),
        ),
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='excellent_re_dsgn_ymd',
            field=models.DateField(blank=True, null=True, verbose_name='모범음식점 재지정일'),
        ),
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='is_excellent_restaurant',
            field=models.BooleanField(db_index=True, default=False, help_text='행정안전부 모범음식점 지정 여부 — MNG_NO 기준 매칭', verbose_name='모범음식점 지정 여부'),
        ),
    ]
