# Generated by Django 6.0.4 on 2026-05-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0014_add_excellent_restaurant_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='ansim_reg_dt',
            field=models.DateField(blank=True, null=True, verbose_name='안심식당 지정일'),
        ),
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='ansim_seq',
            field=models.CharField(blank=True, help_text='RELAX_SEQ — 재동기화 시 중복 방지용', max_length=20, verbose_name='안심식당 일련번호'),
        ),
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='is_ansim_restaurant',
            field=models.BooleanField(db_index=True, default=False, help_text='농림축산식품부 안심식당 현황 — RELAX_SEQ 기준 매칭', verbose_name='안심식당 지정 여부'),
        ),
    ]
