# Generated by Django 6.0.4 on 2026-05-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0015_add_ansim_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='goodprice_menu',
            field=models.CharField(blank=True, help_text='예: 수제돈까스 7000원 / 돈까스정식 8000원', max_length=300, verbose_name='착한가격 메뉴 정보'),
        ),
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='is_goodprice_shop',
            field=models.BooleanField(db_index=True, default=False, help_text='행정안전부 착한가격업소 현황 — 업소명+주소 매칭', verbose_name='착한가격업소 지정 여부'),
        ),
    ]
