# Generated by Django 6.0.4 on 2026-05-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0016_add_goodprice_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicrestaurantdata',
            name='hygiene_grade',
            field=models.CharField(blank=True, help_text='식품의약품안전처 위생등급 인증 (적합) — C004 API 연동', max_length=20, verbose_name='위생등급'),
        ),
    ]
