# Generated by Django 6.0.4 on 2026-05-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0017_alter_publicrestaurantdata_hygiene_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptverification',
            name='extracted_items',
            field=models.JSONField(blank=True, default=list, help_text='예: [{"menu": "삼겹살", "price": 15000}]', verbose_name='추출된 주문 내역'),
        ),
        migrations.AddField(
            model_name='receiptverification',
            name='ocr_analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OCR 분석 완료 시각'),
        ),
        migrations.AddField(
            model_name='receiptverification',
            name='price_discrepancies',
            field=models.JSONField(blank=True, default=list, help_text='예: [{"menu": "삼겹살", "menu_price": 15000, "receipt_price": 17000}]', verbose_name='가격 불일치 항목'),
        ),
        migrations.AddField(
            model_name='receiptverification',
            name='price_match_rate',
            field=models.FloatField(blank=True, help_text='0.0~1.0. null이면 메뉴판 미등록 또는 OCR 미완료', null=True, verbose_name='가격 일치율'),
        ),
        migrations.CreateModel(
            name='RestaurantMenuBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_boards/', verbose_name='메뉴판 이미지')),
                ('status', models.CharField(choices=[('pending', '분석 대기'), ('done', '분석 완료'), ('failed', '분석 실패')], db_index=True, default='pending', max_length=10, verbose_name='분석 상태')),
                ('extracted_prices', models.JSONField(default=dict, verbose_name='추출된 메뉴 가격')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시각')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='분석 완료 시각')),
                ('error_msg', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_boards', to='honest_restaurant.publicrestaurantdata', verbose_name='식당')),
            ],
            options={
                'verbose_name': '메뉴판',
                'verbose_name_plural': '메뉴판',
                'db_table': 'restaurant_menu_board',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
