# Generated by Django 6.0.4 on 2026-05-22 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0018_receiptverification_extracted_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('price', models.PositiveIntegerField(verbose_name='가격(원)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='honest_restaurant.publicrestaurantdata', verbose_name='식당')),
            ],
            options={
                'verbose_name': '메뉴 항목',
                'verbose_name_plural': '메뉴 항목',
                'db_table': 'restaurant_menu_item',
                'ordering': ['name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='RestaurantMenuBoard',
        ),
    ]
