# Generated by Django 6.0.4 on 2026-05-26 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0019_restaurantmenuitem_delete_restaurantmenuboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantmenuitem',
            options={'ordering': ['id'], 'verbose_name': '메뉴 항목', 'verbose_name_plural': '메뉴 항목'},
        ),
    ]
