# Generated by Django 6.0.4 on 2026-05-26 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0021_restaurantmenuitem_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='owner',
            field=models.OneToOneField(blank=True, help_text='우리 가게 등록 시 설정. 1인 1식당 원칙.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_restaurant', to=settings.AUTH_USER_MODEL, verbose_name='사장님'),
        ),
    ]
