# Generated by Django 6.0.4 on 2026-05-26 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0022_add_owner_to_restaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantOwnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_number', models.CharField(blank=True, help_text='입력한 사업자등록번호 (국세청 API 불일치 시 기록)', max_length=12, verbose_name='사업자등록번호')),
                ('cert_image', models.ImageField(upload_to='owner_certs/', verbose_name='사업자등록증 사진')),
                ('status', models.CharField(choices=[('pending', '검토 중'), ('approved', '승인'), ('rejected', '반려')], db_index=True, default='pending', max_length=10, verbose_name='검토 상태')),
                ('admin_note', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일시')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일시')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_applications', to='honest_restaurant.publicrestaurantdata', verbose_name='신청 식당')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_applications', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '사업자 인증 신청',
                'verbose_name_plural': '사업자 인증 신청',
                'db_table': 'restaurant_owner_application',
                'ordering': ['-applied_at'],
            },
        ),
    ]
