# Generated by Django 6.0.4 on 2026-05-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0023_add_owner_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantownerapplication',
            name='verified_by_api',
            field=models.BooleanField(default=False, help_text='True이면 국세청 API에서 계속사업자 확인된 신청', verbose_name='국세청 API 인증 여부'),
        ),
        migrations.AlterField(
            model_name='restaurantownerapplication',
            name='cert_image',
            field=models.ImageField(blank=True, help_text='국세청 API 인증 실패 시 수동 업로드', null=True, upload_to='owner_certs/', verbose_name='사업자등록증 사진'),
        ),
    ]
