# Generated by Django 6.0.4 on 2026-05-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0024_owner_application_cert_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantownerapplication',
            name='approval_notified',
            field=models.BooleanField(default=False, verbose_name='승인 알림 확인 여부'),
        ),
    ]
