# Generated by Django 6.0.4 on 2026-05-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0025_add_approval_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='sns_connected',
            field=models.BooleanField(default=False, help_text='연동 시 마케팅 글 자동 발행(예약/즉시) 기능이 활성화됩니다.', verbose_name='SNS 계정 연동'),
        ),
    ]
