# Generated by Django 6.0.4 on 2026-05-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0026_add_sns_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='가게 상세 페이지에 표시되는 한 줄 소개. 비어 있으면 자동 생성됩니다.', max_length=200, verbose_name='한줄 소개'),
        ),
    ]
