# Generated by Django 6.0.4 on 2026-05-21 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0003_remove_sentiment_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeReviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '분석 대기'), ('done', '분석 완료'), ('failed', '분석 실패')], db_index=True, default='pending', max_length=10, verbose_name='분석 상태')),
                ('is_fake', models.BooleanField(blank=True, null=True, verbose_name='가짜 여부')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='신뢰도')),
                ('translated_text', models.TextField(blank=True, verbose_name='번역된 영문 텍스트')),
                ('penalty_score', models.IntegerField(default=0, verbose_name='부여된 패널티 점수')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='분석 완료 시각')),
                ('error_msg', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fake_review', to='interactions.review', verbose_name='리뷰')),
            ],
            options={
                'verbose_name': '가짜 리뷰 탐지 결과',
                'verbose_name_plural': '가짜 리뷰 탐지 결과',
                'db_table': 'fake_review_result',
            },
        ),
    ]
