# Generated by Django 6.0.4 on 2026-05-13 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('honest_restaurant', '0011_alter_publicrestaurantdata_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_prompt', models.TextField(verbose_name='사장님 입력 키워드/문장')),
                ('generated_content', models.TextField(verbose_name='AI 생성 원본')),
                ('final_content', models.TextField(verbose_name='최종 발행 내용')),
                ('hashtags', models.JSONField(default=list, verbose_name='해시태그 목록')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('naver_blog', '네이버 블로그'), ('kakao_story', '카카오스토리')], max_length=20, verbose_name='발행 플랫폼')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('scheduled', '예약발행'), ('published', '발행완료'), ('failed', '발행실패')], db_index=True, default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='예약 발행 시각')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='실제 발행 시각')),
                ('external_post_id', models.CharField(blank=True, max_length=300, verbose_name='SNS 게시물 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_posts', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_posts', to='honest_restaurant.publicrestaurantdata')),
            ],
            options={
                'verbose_name': '마케팅 게시물',
                'db_table': 'marketing_post',
                'ordering': ['-created_at'],
            },
        ),
    ]
