"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import os
from celery.schedules import crontab

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY            = os.getenv('SECRET_KEY')
SEOUL_API_KEY         = os.getenv('SEOUL_API_KEY',         '')
NATIONAL_API_KEY      = os.getenv('NATIONAL_API_KEY',      '')
NATIONAL_API_URL      = os.getenv('NATIONAL_API_URL',      '')
KAKAO_MAP_API_KEY     = os.getenv('KAKAO_MAP_API_KEY',     '')
KAKAO_REST_API_KEY    = os.getenv('KAKAO_REST_API_KEY',    '')
TOSS_CLIENT_KEY       = os.getenv('TOSS_CLIENT_KEY',       '')
TOSS_SECRET_KEY       = os.getenv('TOSS_SECRET_KEY',       '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = []

# 외부 SDK(카카오맵 등) 로드 시 Referer 헤더 전달을 위해 변경
# same-origin(기본값)은 크로스오리진 요청에 Referer를 보내지 않아 Kakao 403 발생
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',       # 추가
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'allauth',                    # 추가
    'allauth.account',            # 추가
    'allauth.socialaccount',      # 추가
    'allauth.socialaccount.providers.kakao',   # 추가
    'allauth.socialaccount.providers.naver',   # 추가
    'django_filters',
    'honest_restaurant',
    'accounts',
    'interactions',
    'marketing',
    'sales',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.user_role',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True



REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.CookieJWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        "login": "5/minute",   # 로그인 엔드포인트 전용
    },
}

# ── JWT 보안 설정 ──────────────────────────────────────────────────────────────
SIMPLE_JWT = {
    # 토큰 유효기간
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=1440),   # 15분 -> 24시간 (현재 개발용으로 늘려놓음)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),       # 7일 -> 30일 (현재 개발용으로 늘려놓음)

    # 리프레시할 때마다 새 리프레시 토큰 발급 + 기존 토큰 블랙리스트 등록
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    # 알고리즘: HS256 (대칭키, 단일 서버 적합)
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,

    # 토큰 타입 검증 강제
    "VERIFY_EXP": True,

    # 헤더 설정 (Authorization: Bearer <token>)
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",

    # 토큰 내 사용자 식별 필드
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",

    # 쿠키 이름
    "AUTH_COOKIE": "access_token",
    "AUTH_COOKIE_REFRESH": "refresh_token",

    # 쿠키 보안 설정
    "AUTH_COOKIE_SECURE": not DEBUG,        # 개발 환경에서는 False, 운영에서 True (HTTPS 전용)
    "AUTH_COOKIE_HTTP_ONLY": True,          # JS에서 쿠키 접근 불가 (XSS 방어)
    "AUTH_COOKIE_SAMESITE": "Lax",         # CSRF 방어 (크로스사이트 요청 차단)
    "AUTH_COOKIE_PATH": "/",
    "AUTH_COOKIE_DOMAIN": None,             # 운영 시 도메인 명시 권장
}

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

CELERY_BEAT_SCHEDULE = {
    "sync-seoul-restaurants": {
        "task": "honest_restaurant.tasks.daily_sync",
        "schedule": crontab(hour=3, minute=0),  # 매일 새벽 3시
    },
}


# 브라우저에서 접근하는 URL 경로
# ex) http://localhost:8000/static/css/base.css
STATIC_URL = "/static/"
 
# 개발 환경: 프로젝트 루트의 static/ 폴더를 탐색
# (앱 내부 static/ 폴더는 APP_DIRS=True로 자동 탐색됨)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
 
# 배포 환경: collectstatic 명령 시 파일이 모이는 폴더
# (개발 중에는 사용 안 함, 배포 시 필요)
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"

# ── 세션 설정 ──────────────────────────────────────────────────────────────
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2주
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
