# Generated by Django 6.0.4 on 2026-05-22 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0003_remove_sentiment_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '분류 대기'), ('done', '분류 완료'), ('failed', '분류 실패')], db_index=True, default='pending', max_length=10, verbose_name='분류 상태')),
                ('alley_tags', models.JSONField(default=list, help_text='예: ["현지인 추천", "나만 알고 싶은"]', verbose_name='골목장인 태그')),
                ('alley_tag_scores', models.JSONField(default=dict, help_text='예: {"현지인 추천": 0.82, "나만 알고 싶은": 0.71}', verbose_name='골목장인 태그 신뢰도')),
                ('dashboard_tags', models.JSONField(default=list, help_text='예: ["맛있어요", "위생적이에요", "재방문이에요"]', verbose_name='대시보드 태그')),
                ('ai_positive_keywords', models.JSONField(default=list, help_text='예: ["위생", "재방문"]', verbose_name='AI 긍정 카테고리')),
                ('ai_negative_keywords', models.JSONField(default=list, help_text='예: ["응대"]', verbose_name='AI 부정 카테고리')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='분류 완료 시각')),
                ('error_msg', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_classification', to='interactions.review', verbose_name='리뷰')),
            ],
            options={
                'verbose_name': '리뷰 분류 결과',
                'verbose_name_plural': '리뷰 분류 결과',
                'db_table': 'review_classification_result',
            },
        ),
    ]
