# Generated by Django 6.0.4 on 2026-05-22 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_review_classifier', '0001_initial'),
        ('honest_restaurant', '0017_alter_publicrestaurantdata_hygiene_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alley_review_ratio', models.FloatField(default=0.0, verbose_name='골목장인 태그 보유 리뷰 비율')),
                ('is_alley_eligible', models.BooleanField(db_index=True, default=False, verbose_name='골목장인 자격')),
                ('positive_ratio', models.FloatField(default=0.0, verbose_name='긍정 리뷰 비율 (90일)')),
                ('negative_ratio', models.FloatField(default=0.0, verbose_name='부정 리뷰 비율 (90일)')),
                ('ai_score_bonus', models.IntegerField(default=0, verbose_name='AI 보너스 점수')),
                ('ai_score_penalty', models.IntegerField(default=0, verbose_name='AI 패널티 점수')),
                ('ai_net_score', models.IntegerField(db_index=True, default=0, verbose_name='AI 순점수')),
                ('dashboard_tag_summary', models.JSONField(default=dict, verbose_name='전체 태그 빈도')),
                ('top_positive_tags', models.JSONField(default=dict, verbose_name='상위 긍정 태그 Top5')),
                ('top_negative_tags', models.JSONField(default=dict, verbose_name='상위 부정 태그 Top5')),
                ('recent_hygiene_negative_ratio', models.FloatField(default=0.0, verbose_name='최근 14일 위생 부정 비율')),
                ('hygiene_alert', models.BooleanField(db_index=True, default=False, verbose_name='위생 경고')),
                ('review_count_analyzed', models.IntegerField(default=0, verbose_name='집계 기준 리뷰 수')),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='최종 집계 시각')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to='honest_restaurant.publicrestaurantdata', verbose_name='식당')),
            ],
            options={
                'verbose_name': '식당 AI 프로필',
                'verbose_name_plural': '식당 AI 프로필',
                'db_table': 'restaurant_ai_profile',
            },
        ),
    ]
