# Generated by Django 6.0.4 on 2026-05-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_review_classifier', '0002_restaurantaiprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantaiprofile',
            name='price_is_verified',
            field=models.BooleanField(default=False, verbose_name='가격 검증 충분 여부 (30건 이상)'),
        ),
        migrations.AddField(
            model_name='restaurantaiprofile',
            name='price_match_rate',
            field=models.FloatField(default=1.0, verbose_name='가격 일치율 (0~1)'),
        ),
        migrations.AddField(
            model_name='restaurantaiprofile',
            name='price_match_score',
            field=models.IntegerField(default=0, verbose_name='가격일치율 점수 (0/10/15/20)'),
        ),
        migrations.AddField(
            model_name='restaurantaiprofile',
            name='receipt_ocr_count',
            field=models.IntegerField(default=0, verbose_name='OCR 분석된 영수증 수'),
        ),
    ]
