# Generated by Django 6.0.4 on 2026-05-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='주문번호')),
                ('order_name', models.CharField(max_length=255, verbose_name='상품명')),
                ('amount', models.PositiveIntegerField(verbose_name='결제금액')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='결제일시')),
                ('status', models.CharField(default='DONE', max_length=20, verbose_name='결제상태')),
            ],
        ),
    ]
