# Generated by Django 6.0.4 on 2026-05-15 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecord',
            old_name='paid_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='salerecord',
            name='order_name',
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='amount',
            field=models.IntegerField(verbose_name='총 결제금액'),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='status',
            field=models.CharField(default='READY', max_length=20, verbose_name='결제상태'),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('price', models.IntegerField(verbose_name='단가')),
                ('sale_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salerecord')),
            ],
        ),
    ]
