# Generated by Django 6.0.4 on 2026-05-15 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0011_alter_publicrestaurantdata_options_and_more'),
        ('sales', '0005_salerecord_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedrestaurant',
            name='public_restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed', to='honest_restaurant.publicrestaurantdata', verbose_name='공공 데이터 연결'),
        ),
        migrations.AlterField(
            model_name='managedrestaurant',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='사장님 성함'),
        ),
        migrations.AlterField(
            model_name='managedrestaurant',
            name='status',
            field=models.CharField(choices=[('active', '관리 중'), ('inactive', '휴면'), ('pending', '검토 중')], default='pending', max_length=20, verbose_name='상태'),
        ),
    ]
