# Generated by Django 6.0.4 on 2026-05-21 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=100, verbose_name='신뢰 점수')),
                ('fake_count', models.IntegerField(default=0, verbose_name='가짜 리뷰 누적 횟수')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 신뢰 점수',
                'verbose_name_plural': '사용자 신뢰 점수',
                'db_table': 'user_trust_score',
            },
        ),
    ]
