# Generated by Django 6.0.4 on 2026-05-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='gemini-2.5-flash', max_length=100, verbose_name='AI 모델명')),
                ('temperature', models.FloatField(default=1.0, verbose_name='Temperature (0.0 ~ 2.0)')),
                ('role_description', models.TextField(verbose_name='AI 역할 설명')),
                ('writing_instruction', models.TextField(verbose_name='글쓰기 지시사항')),
            ],
            options={
                'verbose_name': 'AI 글 생성 설정',
                'verbose_name_plural': 'AI 글 생성 설정',
                'db_table': 'marketing_ai_config',
            },
        ),
        migrations.CreateModel(
            name='MarketingPlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20, unique=True, verbose_name='플랫폼 ID')),
                ('display_name', models.CharField(max_length=50, verbose_name='표시명')),
                ('guide', models.TextField(verbose_name='작성 가이드')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '플랫폼 설정',
                'verbose_name_plural': '플랫폼 설정',
                'db_table': 'marketing_platform_config',
                'ordering': ['order', 'platform'],
            },
        ),
    ]
