# Generated by Django 6.0.4 on 2026-05-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRestaurantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_no', models.CharField(help_text='서울시 공공DB 원본 식별자 (내부용, 사용자 노출 불필요)', max_length=50, unique=True, verbose_name='관리번호')),
                ('name', models.CharField(help_text='[필수] 사업자등록증 명칭과 자동 대조 → LV2 검증', max_length=200, verbose_name='업소명')),
                ('address_road', models.CharField(blank=True, help_text='[필수] 지도 핀 표시 + 사장님 주소 진위 확인 (LV2)', max_length=300, verbose_name='도로명주소')),
                ('address_jibun', models.CharField(blank=True, help_text='[필수] 도로명 주소 보완용', max_length=300, verbose_name='지번주소')),
                ('district', models.CharField(blank=True, db_index=True, help_text='[필수] 1단계 MVP 종로구 필터링, 이후 구별 확장 대응 / 상권별 분석 & 지자체 B2G 리포트', max_length=20, verbose_name='자치구')),
                ('phone', models.CharField(blank=True, help_text='[권장] 고객 앱 연결 + 사장님 연락처 진위 확인', max_length=30, verbose_name='전화번호')),
                ('business_type', models.CharField(blank=True, db_index=True, help_text='[필수] 식당 카테고리 자동 분류 (한식/중식/분식 등) → 검색 필터 + AI 콘텐츠 생성 시 업종 컨텍스트', max_length=100, verbose_name='업태구분명')),
                ('category_name', models.CharField(blank=True, help_text='[필수] 세부 업종명 (업태구분명의 하위 분류)', max_length=100, verbose_name='업종명')),
                ('sanitation_business_type', models.CharField(blank=True, help_text="[필수] 식품위생법상 업종 확인 → 위생 등급 라벨 기준 / '일반음식점' 여부로 착한가격업소 신청 자격 판단", max_length=100, verbose_name='위생업종명')),
                ('license_date', models.DateField(blank=True, db_index=True, help_text="[필수] 영업 기간 계산 → LV4 '6개월 이상 안정적 운영' 조건 / 노포 판별(10년+) → 아카이브 프로젝트 자동 추천", null=True, verbose_name='인허가일자')),
                ('license_cancel_date', models.DateField(blank=True, help_text='[필수] 폐업·취소 가게 자동 감지 → 검증 배지 즉시 회수 / 매일 배치(Celery beat)로 상태 동기화', null=True, verbose_name='인허가취소일자')),
                ('status_code', models.CharField(blank=True, choices=[('01', '영업'), ('02', '휴업'), ('03', '폐업')], db_index=True, help_text='[필수] 폐업·취소 가게 자동 감지 → 검증 배지 즉시 회수', max_length=10, verbose_name='영업상태구분코드')),
                ('area', models.FloatField(blank=True, help_text='[선택] 착한가격업소 신청 요건(면적 기준) 자동 판단 보조', null=True, verbose_name='소재지면적(㎡)')),
                ('last_modified_at', models.DateTimeField(blank=True, help_text='[권장] 공공 DB 최신 업데이트 여부 추적 → 캐싱 전략 기준', null=True, verbose_name='최종수정시점')),
                ('latitude', models.FloatField(blank=True, help_text='[필수] 고객 앱 지도에 가게 핀 표시 / 반경 1km 재고 나눔 마켓 (사장님 앱 모듈2)', null=True, verbose_name='위도 (WGS84)')),
                ('longitude', models.FloatField(blank=True, help_text='[필수] 고객 앱 지도에 가게 핀 표시 / 반경 1km 재고 나눔 마켓 (사장님 앱 모듈2)', null=True, verbose_name='경도 (WGS84)')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Celery beat 매일 새벽 3시 자동 갱신', verbose_name='우리 서버 동기화 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 수집 시각')),
            ],
            options={
                'verbose_name': '서울시 공공 식당 데이터',
                'verbose_name_plural': '서울시 공공 식당 데이터',
                'db_table': 'public_restaurant_data',
                'ordering': ['-synced_at'],
                'indexes': [models.Index(fields=['district', 'status_code'], name='idx_district_status'), models.Index(fields=['latitude', 'longitude'], name='idx_lat_lng'), models.Index(fields=['license_date'], name='idx_license_date')],
            },
        ),
    ]
