# Generated by Django 6.0.4 on 2026-05-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0003_receiptverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptverification',
            name='comment',
            field=models.TextField(blank=True, verbose_name='한 줄 후기'),
        ),
        migrations.AddField(
            model_name='receiptverification',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='영수증 이미지'),
        ),
    ]
