# Generated by Django 6.0.4 on 2026-05-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0006_alter_publicrestaurantdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrestaurantdata',
            name='restaurant_type',
            field=models.CharField(choices=[('일반음식점', '일반음식점'), ('휴게음식점', '휴게음식점')], db_index=True, default='일반음식점', max_length=20, verbose_name='음식점 유형'),
        ),
    ]
