# Generated by Django 6.0.4 on 2026-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest_restaurant', '0008_add_unique_name_road_biztype'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publicrestaurantdata',
            index=models.Index(fields=['status_code', 'synced_at'], name='idx_status_synced'),
        ),
        migrations.AddIndex(
            model_name='publicrestaurantdata',
            index=models.Index(fields=['district', 'status_code', 'synced_at'], name='idx_district_status_synced'),
        ),
        migrations.AddIndex(
            model_name='publicrestaurantdata',
            index=models.Index(fields=['business_type', 'status_code', 'synced_at'], name='idx_biztype_status_synced'),
        ),
        migrations.AddIndex(
            model_name='publicrestaurantdata',
            index=models.Index(fields=['name'], name='idx_name'),
        ),
    ]
