# Generated by Django 6.0.4 on 2026-05-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_remove_sentiment_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/', verbose_name='리뷰 이미지'),
        ),
    ]
