# Generated by Django 6.0.4 on 2026-05-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/', verbose_name='리뷰 이미지 2'),
        ),
        migrations.AddField(
            model_name='review',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/', verbose_name='리뷰 이미지 3'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/', verbose_name='리뷰 이미지 1'),
        ),
    ]
