# Generated by Django 6.0.4 on 2026-05-15 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_paid_at_salerecord_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='상담 일자')),
                ('category', models.CharField(choices=[('sales', '매출 분석'), ('menu', '메뉴 전략'), ('marketing', '마케팅'), ('pricing', '가격 정책'), ('other', '기타')], max_length=20, verbose_name='분류')),
                ('content', models.TextField(verbose_name='상담 내용')),
                ('next_action', models.TextField(blank=True, verbose_name='다음 액션')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='다음 상담 예정일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': '상담 기록',
                'verbose_name_plural': '상담 기록',
                'ordering': ['-date'],
            },
        ),
    ]
