# Generated by Django 6.0.4 on 2026-05-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_consultingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상호명')),
                ('owner_name', models.CharField(max_length=50, verbose_name='사장님 성함')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('business_type', models.CharField(blank=True, max_length=50, verbose_name='업종')),
                ('status', models.CharField(choices=[('active', '관리 중'), ('inactive', '휴면'), ('pending', '검토 중')], default='active', max_length=20, verbose_name='상태')),
                ('joined_at', models.DateField(verbose_name='등록일')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
            ],
            options={
                'verbose_name': '관리 매장',
                'verbose_name_plural': '관리 매장',
                'ordering': ['-joined_at'],
            },
        ),
    ]
