# Generated by Django 6.0.4 on 2026-05-15 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_managedrestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_records', to='sales.managedrestaurant', verbose_name='관리 매장'),
        ),
    ]
